services:
  postgres:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: manastats_admin_toni
      POSTGRES_PASSWORD: purpura123**
      POSTGRES_DB: mana_stats
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: manastats
    restart: always
    ports:
      - "3000:3000"
      - "5555:5555"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://manastats_admin_toni:purpura123**@postgres:5432/mana_stats"
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
