import "../../styles/globals.scss";

import { Geist, Geist_Mono } from "next/font/google";

import { NextIntlClientProvider } from 'next-intl';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata = {
  title: "ManaStats",
  description: "Generated by create next app",
};

export default async function LocaleLayout({ children, params }) {
  const { locale } = await params;


  return (
    <html lang={locale}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <NextIntlClientProvider>{children}</NextIntlClientProvider>
      </body>
    </html>
  );
}